### ISSUE TITLE
Methods/Results Section Feedback

### ISSUE THREAD

**Issue by ghost** [ChihYuChiang/MACS30200proj#3]
It’s obvious the amount of work you put into this write-up. While it is a highly detailed and well constructed write-up of your research design, it is far too long for a methods/results section.  A lot of the background information can be cut out. For example, instead of individual sub-sections for “Core Game Selection,” “Triplet Survey on In-game Experience,” etc., included a single sentence (or two at most) about that part of the process. In general, you want to convey three main components of your research design and methodology: (1) defining the data and methods; (2) presenting descriptive data results; and (3) the results and analysis of your computational method.

**Comment by ChihYuChiang** [comment]
Hi Laila,
Thanks for your feedback.
For this project, I really found it difficult to clearly present the materials in the 3 ordinary sections/components as you mentioned, due to the complexity of its process, multiple data sources and methods. Do you think it is feasible that I still retain the current structure (instead of the 3 sections) while moving some of the details to appendix to make the piece shorter? Should those details still be included as for the replicability purpose Dr. Evans repeatedly stressed in the class?

**Comment by ghost** [comment]
I think it’s fine to keep the structure as is if most of the background information is moved to the appendix. You don’t necessarily need to name the three sections as I mentioned, but you do want to be sure that you highlight the relevant information in each section. As it reads now, this seems to be more of a methods paper, as opposed to a computational research paper using a particular methodology. In fact, I would encourage you to speak with Dr. Evans about the appendix. I am not sure you need all that information you provide, but better to check with him as he will be grading your final paper. 

Let me know if you have any other questions!
Laila 


—
Laila H. Noureldin, MEd, MA
Doctoral Student | Sociology, PhD
The University of Chicago

**Comment by ChihYuChiang** [comment]
Hi Laila,
Thanks for the instant response. I will try to do so!
For me, this work is, indeed, a research exploring some methods to try to provide a reasonable scheme to analyze the underlined phenomena. Is this not appropriate to this course..? : (
Best,
Chih-Yu

**Comment by ghost** [comment]
Hi Chih-Yu,

I didn't mean to suggest that it is not appropriate for the course. I just want to make sure your method is approved by either Dr. Evans or Dr. Soltoff. Hopefully, they could provide more concrete feedback on how you can cut down the current draft to fit the length of a peer-reviewed article. 

—
Laila H. Noureldin, MEd, MA
Doctoral Student | Sociology, PhD
The University of Chicago

**Comment by ChihYuChiang** [comment]
Hi Laila,

I got it. I'll secure a meeting with them as soon as possible.
Thanks for all your feedback and responses. : )

Best,
Chih-Yu
